# Generated by Django 6.0 on 2025-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlresult",
            name="status_code",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="crawlresult",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
