# Generated by Django 6.0 on 2025-12-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_app", "0003_deleterequest"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="crawlresult",
            table="crawled",
        ),
    ]
