# Generated by Django 6.0 on 2025-12-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_app", "0005_crawllog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deleterequest",
            name="user",
        ),
    ]
