# Generated by Django 6.0 on 2025-12-26 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_app", "0006_remove_deleterequest_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM crawled;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="crawlresult",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name="crawlresult",
            unique_together={("user", "url")},
        ),
    ]
